// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

Texture2D<float> Attempt, Template;
RWTexture2D<float> Result;

[numthreads(8,8,1)]
void CSMain (uint2 id : SV_DispatchThreadID)
{
	float diff = Attempt [id] - Template [id];
	if (diff < 0) {
		diff = diff * -1;
	}
	Result[id] = diff;
}